#!/bin/bash

arg=$1 ;
argc=$# ;

if [ "$argc" -gt 1 ]; then
	echo "./build"
	echo "./build [run/clean]" ;
	exit 0 ;
fi
		
if ! [[ "$arg" = "clean" || "$arg" = "run" || -z "$arg" ]]; then
	echo "./build"
	echo "./build [run/clean]" ;
	exit 0 ;
fi

if [ "$arg" = "clean" ]; then
	# clean the python glue
	rm -rf pyglue/*.class ;
	# clean the ec part
	rm -rf evomutex/*.class evomutex/*/*.class;
	exit 0 ;
elif [ "$arg" = "run" ]; then
	# run the test code
	java -classpath .:pyglue/*:../lib/* pyglue.PyGlue ;
	# run the ec code
	java -classpath .:../:pyglue/*:evomutex/*:../lib/* ec.Evolve -file evomutex/evomutex.params ;	
else
	# build the python glue
	javac -classpath .:pyglue/*:../lib/* pyglue/*.java ;
	# build the ec code 
	javac -classpath .:pyglue/*:evomutex/*:../lib/* evomutex/*.java evomutex/*/*.java;
fi

